/**
 * Affix pools. Magic items roll prefixes ("Gleaming", "Emberforged") and
 * suffixes ("of the Ember Fox", "of Stillwater") that add stat mods. Each
 * affix has five tiers; the tier rolled depends on item level, so a level-30
 * "Keen" blade is much sharper than a level-3 one, and the tier also picks
 * the name word (Sharp → Keen → Razor → Vorpal → Soulreaver).
 *
 * Suffix names are partly generated: a theme combines an evocative adjective
 * with an animal/spirit noun, giving "of the Ember Fox", "of the Drowned
 * Heron"... so even the same affix reads differently across items.
 *
 * Shared (server + client).
 */
import type { StatMods } from '../types';
import type { Rng } from '../../core/rng';

/** Which kinds of items an affix may appear on. */
export type AffixTarget = 'melee' | 'ranged' | 'focus' | 'shield' | 'armor' | 'clothing' | 'jewelry' | 'trinket' | 'tool' | 'light';

export interface AffixDef {
  id: string;
  prefix: boolean;
  /** Name per tier 0..4 (prefix adjectives or suffix phrases). Suffix names may be generated by `theme`. */
  names: string[];
  targets: AffixTarget[];
  /** Mods at tier t (0..4) with a roll r in [0,1] for in-tier variance. */
  mods: (t: number, r: number) => StatMods;
  /** Relative frequency. */
  weight: number;
  /** Minimum item level. */
  minLevel?: number;
  /** Generated suffix flavour: picks "of the <adj> <noun>" from these pools. */
  theme?: { adj: string[]; noun: string[] };
  /** Granted ability (enchant procs, interpreted by gameplay). */
  grants?: (t: number) => string | undefined;
  /** Visual glow color for enchantments (sRGB). */
  glow?: [number, number, number];
  /** Group: two affixes of the same group never roll together. */
  group: string;
}

const lerpT = (t: number, r: number, lo: number, hi: number) => {
  // Five tiers spread across [lo, hi]; r adds in-tier variance.
  const step = (hi - lo) / 5;
  return lo + step * (t + r);
};
const R1 = (v: number) => Math.round(v);
const R2 = (v: number) => Math.round(v * 100) / 100;

const MELEE: AffixTarget[] = ['melee'];
const WEAPONS: AffixTarget[] = ['melee', 'ranged'];
const WORN: AffixTarget[] = ['armor', 'clothing', 'shield'];
const ANYWEAR: AffixTarget[] = ['armor', 'clothing', 'jewelry', 'trinket', 'shield'];

export const AFFIXES: AffixDef[] = [
  // ---------------------------------------------------------------- weapon prefixes
  { id: 'keen', prefix: true, group: 'phys', names: ['Sharp', 'Keen', 'Razor', 'Vorpal', 'Soulreaver'], targets: MELEE, weight: 10, mods: (t, r) => ({ 'damage.slash': R1(lerpT(t, r, 2, 18)), critChance: R2(0.01 + t * 0.01) }) },
  { id: 'heavy', prefix: true, group: 'phys', names: ['Weighted', 'Heavy', 'Crushing', 'Ruinous', 'Worldbreaker'], targets: MELEE, weight: 8, mods: (t, r) => ({ 'damage.blunt': R1(lerpT(t, r, 2, 20)) }) },
  { id: 'piercing', prefix: true, group: 'phys', names: ['Pointed', 'Piercing', 'Impaling', 'Skewering', 'Heartseeker'], targets: WEAPONS, weight: 8, mods: (t, r) => ({ 'damage.pierce': R1(lerpT(t, r, 2, 18)) }) },
  { id: 'swift', prefix: true, group: 'speed', names: ['Light', 'Swift', 'Quicksilver', 'Blurring', 'Windborne'], targets: WEAPONS, weight: 7, mods: (t, r) => ({ attackSpeed: R2(lerpT(t, r, 0.03, 0.22)) }) },
  { id: 'cruel', prefix: true, group: 'crit', names: ['Cruel', 'Vicious', 'Savage', 'Merciless', 'Butcher\'s'], targets: WEAPONS, weight: 6, mods: (t, r) => ({ critChance: R2(lerpT(t, r, 0.02, 0.14)) }) },
  { id: 'flaming', prefix: true, group: 'elem', names: ['Smouldering', 'Flaming', 'Emberforged', 'Infernal', 'Sunfire'], targets: WEAPONS, weight: 6, glow: [1, 0.45, 0.12], mods: (t, r) => ({ 'damage.fire': R1(lerpT(t, r, 2, 22)) }), grants: (t) => (t >= 3 ? 'ench.flame_burst' : undefined) },
  { id: 'freezing', prefix: true, group: 'elem', names: ['Chilled', 'Frosted', 'Rimebound', 'Glacial', 'Winterheart'], targets: WEAPONS, weight: 6, glow: [0.5, 0.8, 1], mods: (t, r) => ({ 'damage.frost': R1(lerpT(t, r, 2, 20)) }), grants: (t) => (t >= 3 ? 'ench.frost_bite' : undefined) },
  { id: 'shocking', prefix: true, group: 'elem', names: ['Crackling', 'Sparking', 'Stormcalled', 'Thunderous', 'Skyfury'], targets: WEAPONS, weight: 5, glow: [0.7, 0.75, 1], mods: (t, r) => ({ 'damage.shock': R1(lerpT(t, r, 2, 22)) }), grants: (t) => (t >= 3 ? 'ench.chain_spark' : undefined) },
  { id: 'venomous', prefix: true, group: 'elem', names: ['Tainted', 'Venomous', 'Viperfang', 'Blighted', 'Plaguebringer'], targets: WEAPONS, weight: 5, glow: [0.45, 0.9, 0.2], mods: (t, r) => ({ 'damage.poison': R1(lerpT(t, r, 2, 18)) }) },
  { id: 'holy', prefix: true, group: 'elem', names: ['Blessed', 'Hallowed', 'Radiant', 'Sanctified', 'Dawnsworn'], targets: [...WEAPONS, 'focus'], weight: 4, glow: [1, 0.92, 0.6], mods: (t, r) => ({ 'damage.radiant': R1(lerpT(t, r, 2, 18)), 'resist.shadow': R1(lerpT(t, r, 2, 10)) }) },
  { id: 'shadow', prefix: true, group: 'elem', names: ['Dusky', 'Shadowed', 'Nightforged', 'Umbral', 'Voidtouched'], targets: [...WEAPONS, 'focus'], weight: 4, glow: [0.55, 0.25, 0.9], mods: (t, r) => ({ 'damage.shadow': R1(lerpT(t, r, 2, 18)), stealth: R1(lerpT(t, r, 1, 6)) }) },
  { id: 'vampiric', prefix: true, group: 'leech', names: ['Thirsting', 'Leeching', 'Vampiric', 'Bloodbound', 'Heartdrinker'], targets: MELEE, weight: 3, minLevel: 8, glow: [0.7, 0.05, 0.1], mods: (t, r) => ({ hpRegen: R2(lerpT(t, r, 0.2, 1.5)), 'damage.shadow': R1(lerpT(t, r, 1, 8)) }), grants: (t) => (t >= 2 ? 'ench.lifesteal' : undefined) },
  { id: 'arcane', prefix: true, group: 'spell', names: ['Humming', 'Arcane', 'Spellwoven', 'Mystic', 'Archmagus\''], targets: ['focus'], weight: 10, glow: [0.6, 0.5, 1], mods: (t, r) => ({ spellPower: R2(lerpT(t, r, 0.04, 0.3)) }) },
  { id: 'channeling', prefix: true, group: 'cast', names: ['Focused', 'Channeling', 'Resonant', 'Attuned', 'Starbound'], targets: ['focus', 'jewelry'], weight: 7, mods: (t, r) => ({ castSpeed: R2(lerpT(t, r, 0.03, 0.2)), maxMana: R1(lerpT(t, r, 5, 30)) }) },
  { id: 'masterwork_tool', prefix: true, group: 'tool', names: ['Handy', 'Efficient', 'Artisan\'s', 'Master\'s', 'Grandmaster\'s'], targets: ['tool'], weight: 10, mods: (t, r) => ({ ['skill.' + ['mining', 'woodcutting', 'herbalism', 'smithing', 'cooking'][Math.floor(r * 5)]]: R1(lerpT(t, 0.5, 2, 15)) }) },
  { id: 'bright', prefix: true, group: 'light', names: ['Bright', 'Radiant', 'Brilliant', 'Dazzling', 'Sunlit'], targets: ['light'], weight: 10, mods: (t, r) => ({ lightRadius: R1(lerpT(t, r, 2, 12)) }) },

  // ---------------------------------------------------------------- armor prefixes
  { id: 'sturdy', prefix: true, group: 'def', names: ['Sturdy', 'Reinforced', 'Bulwark', 'Fortified', 'Unbreakable'], targets: WORN, weight: 10, mods: (t, r) => ({ armor: R1(lerpT(t, r, 1, 14)) }) },
  { id: 'vital', prefix: true, group: 'life', names: ['Hale', 'Vigorous', 'Stalwart', 'Titan\'s', 'Undying'], targets: ANYWEAR, weight: 8, mods: (t, r) => ({ maxHp: R1(lerpT(t, r, 5, 60)) }) },
  { id: 'nimble', prefix: true, group: 'move', names: ['Nimble', 'Fleet', 'Windstep', 'Galeborn', 'Quickening'], targets: ['armor', 'clothing'], weight: 5, mods: (t, r) => ({ moveSpeed: R2(lerpT(t, r, 0.02, 0.1)) }) },
  { id: 'shadowed_armor', prefix: true, group: 'stealth', names: ['Quiet', 'Muffled', 'Shadowed', 'Ghostly', 'Unseen'], targets: ['armor', 'clothing', 'trinket'], weight: 5, mods: (t, r) => ({ stealth: R1(lerpT(t, r, 2, 15)) }) },
  { id: 'warded', prefix: true, group: 'resall', names: ['Warded', 'Charmed', 'Abjuring', 'Aegis', 'Sanctum'], targets: ANYWEAR, weight: 4, minLevel: 6, glow: [0.6, 0.8, 1], mods: (t, r) => {
    const v = R1(lerpT(t, r, 2, 10));
    return { 'resist.fire': v, 'resist.frost': v, 'resist.shock': v, 'resist.poison': v };
  } },
  { id: 'mystic_wear', prefix: true, group: 'spell', names: ['Glimmering', 'Mystic', 'Sorcerous', 'Eldritch', 'Archon\'s'], targets: ['clothing', 'jewelry', 'trinket'], weight: 6, glow: [0.6, 0.5, 1], mods: (t, r) => ({ spellPower: R2(lerpT(t, r, 0.02, 0.18)), maxMana: R1(lerpT(t, r, 5, 25)) }) },
  { id: 'enduring', prefix: true, group: 'stam', names: ['Tireless', 'Enduring', 'Marathon', 'Indefatigable', 'Everlasting'], targets: ANYWEAR, weight: 6, mods: (t, r) => ({ maxStamina: R1(lerpT(t, r, 5, 50)), staminaRegen: R2(lerpT(t, r, 0.2, 2)) }) },

  // ---------------------------------------------------------------- suffixes
  { id: 'of_bear', prefix: false, group: 's_hp', names: ['of the Cub', 'of the Bear', 'of the Cave Bear', 'of the Great Bear', 'of the Bear King'], targets: ANYWEAR, weight: 8, mods: (t, r) => ({ maxHp: R1(lerpT(t, r, 6, 70)) }), theme: { adj: ['Stout', 'Old', 'Iron', 'Mountain', 'Grizzled'], noun: ['Bear', 'Bison', 'Aurochs', 'Oak', 'Ox'] } },
  { id: 'of_ember', prefix: false, group: 's_fire', names: ['of Warmth', 'of Embers', 'of the Pyre', 'of the Furnace', 'of the Phoenix'], targets: [...ANYWEAR, ...WEAPONS], weight: 6, glow: [1, 0.45, 0.12], mods: (t, r) => ({ 'resist.fire': R1(lerpT(t, r, 4, 30)) }), theme: { adj: ['Ember', 'Ashen', 'Smouldering', 'Cinder', 'Scorched'], noun: ['Fox', 'Salamander', 'Hearth', 'Phoenix', 'Moth'] } },
  { id: 'of_frost', prefix: false, group: 's_frost', names: ['of the Thaw', 'of Frost', 'of the Glacier', 'of the White Waste', 'of Endless Winter'], targets: [...ANYWEAR, ...WEAPONS], weight: 6, glow: [0.5, 0.8, 1], mods: (t, r) => ({ 'resist.frost': R1(lerpT(t, r, 4, 30)) }), theme: { adj: ['Winter', 'Rime', 'Snowbound', 'Pale', 'Frozen'], noun: ['Wolf', 'Owl', 'Hare', 'Lake', 'Stag'] } },
  { id: 'of_storm', prefix: false, group: 's_shock', names: ['of Static', 'of the Storm', 'of Thunder', 'of the Tempest', 'of the Sky Father'], targets: [...ANYWEAR, ...WEAPONS], weight: 5, glow: [0.7, 0.75, 1], mods: (t, r) => ({ 'resist.shock': R1(lerpT(t, r, 4, 30)) }), theme: { adj: ['Storm', 'Thunder', 'Restless', 'Howling', 'Grey'], noun: ['Hawk', 'Eagle', 'Gale', 'Heron', 'Peak'] } },
  { id: 'of_antidote', prefix: false, group: 's_poison', names: ['of Cleansing', 'of the Antidote', 'of the Serpent', 'of the Basilisk', 'of Purity'], targets: ANYWEAR, weight: 5, mods: (t, r) => ({ 'resist.poison': R1(lerpT(t, r, 4, 30)) }), theme: { adj: ['Green', 'Marsh', 'Coiled', 'Bitter', 'Drowned'], noun: ['Serpent', 'Toad', 'Adder', 'Spider', 'Heron'] } },
  { id: 'of_dawn', prefix: false, group: 's_shadow', names: ['of Candlelight', 'of the Dawn', 'of the Lantern', 'of the Sun', 'of the Unconquered Sun'], targets: ANYWEAR, weight: 4, mods: (t, r) => ({ 'resist.shadow': R1(lerpT(t, r, 4, 30)), lightRadius: R1(t) }), theme: { adj: ['Golden', 'Rising', 'Gilded', 'Bright', 'Morning'], noun: ['Lark', 'Lion', 'Sun', 'Candle', 'Stag'] } },
  { id: 'of_mind', prefix: false, group: 's_psy', names: ['of Calm', 'of the Mind', 'of the Sage', 'of the Unbroken Will', 'of the Silent Oracle'], targets: ANYWEAR, weight: 4, mods: (t, r) => ({ 'resist.psychic': R1(lerpT(t, r, 4, 30)), perception: R1(t * 2) }), theme: { adj: ['Silent', 'Patient', 'Still', 'Far-seeing', 'Dreaming'], noun: ['Owl', 'Sage', 'Monk', 'Moon', 'Raven'] } },
  { id: 'of_mana', prefix: false, group: 's_mana', names: ['of Insight', 'of the Magi', 'of Wizardry', 'of the Archmage', 'of the Astral Sea'], targets: [...ANYWEAR, 'focus'], weight: 7, mods: (t, r) => ({ maxMana: R1(lerpT(t, r, 6, 60)), manaRegen: R2(lerpT(t, r, 0.1, 1.2)) }), theme: { adj: ['Starlit', 'Wandering', 'Hidden', 'Azure', 'Dreaming'], noun: ['Moth', 'Star', 'Comet', 'Raven', 'Tide'] } },
  { id: 'of_vigor', prefix: false, group: 's_regen', names: ['of Mending', 'of Vigor', 'of Renewal', 'of the Troll', 'of Rebirth'], targets: ANYWEAR, weight: 5, mods: (t, r) => ({ hpRegen: R2(lerpT(t, r, 0.2, 2.5)) }), theme: { adj: ['Green', 'Spring', 'Mossy', 'Deep-rooted', 'Evergreen'], noun: ['Troll', 'Willow', 'Hart', 'Fern', 'Oak'] } },
  { id: 'of_wind', prefix: false, group: 's_move', names: ['of the Breeze', 'of the Wind', 'of the Gale', 'of the Swift Hunt', 'of the Four Winds'], targets: ['armor', 'clothing', 'jewelry', 'trinket'], weight: 4, mods: (t, r) => ({ moveSpeed: R2(lerpT(t, r, 0.02, 0.1)), jump: R2(lerpT(t, r, 0.02, 0.12)) }), theme: { adj: ['Swift', 'Wandering', 'Restless', 'Leaping', 'Wild'], noun: ['Hare', 'Deer', 'Swallow', 'Fox', 'Hound'] } },
  { id: 'of_shadows', prefix: false, group: 's_stealth', names: ['of Hiding', 'of Shadows', 'of the Night', 'of the Unseen Hand', 'of the Moonless Sky'], targets: ['armor', 'clothing', 'jewelry', 'trinket', 'melee'], weight: 5, mods: (t, r) => ({ stealth: R1(lerpT(t, r, 2, 16)) }), theme: { adj: ['Silent', 'Hidden', 'Velvet', 'Moonless', 'Creeping'], noun: ['Cat', 'Mouse', 'Spider', 'Viper', 'Owl'] } },
  { id: 'of_eagle', prefix: false, group: 's_perc', names: ['of Watching', 'of the Hawk', 'of the Eagle', 'of the Hunter', 'of the All-Seeing Eye'], targets: ['armor', 'clothing', 'jewelry', 'trinket', 'ranged'], weight: 5, mods: (t, r) => ({ perception: R1(lerpT(t, r, 2, 18)) }), theme: { adj: ['Watchful', 'Keen-eyed', 'High', 'Circling', 'Hunting'], noun: ['Eagle', 'Hawk', 'Falcon', 'Lynx', 'Kestrel'] } },
  { id: 'of_mule', prefix: false, group: 's_carry', names: ['of the Porter', 'of the Mule', 'of the Ox', 'of the Caravan', 'of the Titan'], targets: ['armor', 'clothing', 'trinket'], weight: 4, mods: (t, r) => ({ carry: R1(lerpT(t, r, 5, 50)) }), theme: { adj: ['Patient', 'Broad-backed', 'Laden', 'Stubborn', 'Tireless'], noun: ['Mule', 'Ox', 'Camel', 'Yak', 'Beetle'] } },
  { id: 'of_slaying', prefix: false, group: 's_dmg', names: ['of Wounding', 'of Slaying', 'of Carnage', 'of Slaughter', 'of the Red Harvest'], targets: WEAPONS, weight: 6, mods: (t, r) => ({ critChance: R2(lerpT(t, r, 0.02, 0.1)), 'damage.slash': R1(lerpT(t, r, 1, 8)) }), theme: { adj: ['Red', 'Hungry', 'Grim', 'Howling', 'Crimson'], noun: ['Wolf', 'Shrike', 'Boar', 'Lion', 'Raven'] } },
  { id: 'of_quickness', prefix: false, group: 's_speed', names: ['of Haste', 'of Quickness', 'of Alacrity', 'of the Blur', 'of Lightning Reflexes'], targets: [...WEAPONS, 'jewelry'], weight: 5, mods: (t, r) => ({ attackSpeed: R2(lerpT(t, r, 0.02, 0.15)) }), theme: { adj: ['Darting', 'Flickering', 'Restless', 'Swift', 'Blinking'], noun: ['Hummingbird', 'Wasp', 'Mongoose', 'Swallow', 'Viper'] } },
  { id: 'of_skill_blades', prefix: false, group: 's_skill', names: ['of the Duelist', 'of the Fencer', 'of the Bladedancer', 'of the Swordsaint', 'of the Thousand Cuts'], targets: ['melee', 'jewelry', 'armor'], weight: 3, mods: (t, r) => ({ 'skill.blades': R1(lerpT(t, r, 2, 15)) }) },
  { id: 'of_skill_archery', prefix: false, group: 's_skill', names: ['of the Fletcher', 'of the Archer', 'of the Marksman', 'of the Sharpshooter', 'of the Unerring Shaft'], targets: ['ranged', 'jewelry', 'armor', 'clothing'], weight: 3, mods: (t, r) => ({ 'skill.archery': R1(lerpT(t, r, 2, 15)) }) },
  { id: 'of_skill_smith', prefix: false, group: 's_skill', names: ['of the Apprentice', 'of the Smith', 'of the Forgemaster', 'of the Anvil-Lord', 'of the Worldforge'], targets: ['tool', 'clothing', 'jewelry'], weight: 3, mods: (t, r) => ({ 'skill.smithing': R1(lerpT(t, r, 2, 15)) }) },
  { id: 'of_skill_herb', prefix: false, group: 's_skill', names: ['of the Gatherer', 'of the Herbalist', 'of the Green Hand', 'of the Druid', 'of the Hedge-Queen'], targets: ['tool', 'clothing', 'jewelry', 'trinket'], weight: 3, mods: (t, r) => ({ 'skill.herbalism': R1(lerpT(t, r, 2, 15)), 'skill.foraging': R1(lerpT(t, r, 1, 8)) }) },
  { id: 'of_skill_mining', prefix: false, group: 's_skill', names: ['of the Digger', 'of the Miner', 'of the Deep Delver', 'of the Mountain King', 'of the Undermountain'], targets: ['tool', 'armor', 'jewelry'], weight: 3, mods: (t, r) => ({ 'skill.mining': R1(lerpT(t, r, 2, 15)) }) },
  { id: 'of_barter', prefix: false, group: 's_social', names: ['of the Peddler', 'of the Merchant', 'of the Guildmaster', 'of the Merchant Prince', 'of Golden Tongues'], targets: ['jewelry', 'clothing', 'trinket'], weight: 3, mods: (t, r) => ({ 'skill.barter': R1(lerpT(t, r, 2, 15)), 'skill.speech': R1(lerpT(t, r, 1, 8)) }) },
  { id: 'of_warding', prefix: false, group: 's_armor', names: ['of Protection', 'of Warding', 'of the Bastion', 'of the Citadel', 'of the Unyielding'], targets: [...WORN, 'jewelry'], weight: 6, mods: (t, r) => ({ armor: R1(lerpT(t, r, 1, 12)) }), theme: { adj: ['Stone', 'Iron', 'Shelled', 'Walled', 'Armoured'], noun: ['Tortoise', 'Pangolin', 'Crab', 'Bastion', 'Boar'] } },
  { id: 'of_burning', prefix: false, group: 's_ench', names: ['of Burning', 'of Immolation', 'of Wildfire', 'of the Inferno', 'of the Dragon\'s Breath'], targets: WEAPONS, weight: 3, minLevel: 10, glow: [1, 0.4, 0.1], mods: (t, r) => ({ 'damage.fire': R1(lerpT(t, r, 3, 16)) }), grants: (t) => (t >= 2 ? 'ench.ignite' : undefined) },
];

const BY_ID = new Map(AFFIXES.map((a) => [a.id, a]));
export function affixDef(id: string) {
  return BY_ID.get(id);
}

/**
 * Display name for an affix at tier t. Themed suffixes sometimes use a
 * generated "of the <Adj> <Noun>" instead of the fixed tier phrase.
 */
export function affixName(a: AffixDef, t: number, rng: Rng): string {
  if (!a.prefix && a.theme && rng.chance(0.45)) return `of the ${rng.pick(a.theme.adj)} ${rng.pick(a.theme.noun)}`;
  return a.names[Math.max(0, Math.min(a.names.length - 1, t))];
}
