/**
 * Validates the command registry (src/client/commands.ts) and keeps the README controls
 * section derived from it.
 *
 *  - ids unique; every command has a label, short caption and an existing glyph
 *  - no binding is used by two commands (except the shared Esc of pause / clear target,
 *    which the UI resolves: first Esc clears a target, the next one pauses)
 *  - rebindable commands name an existing ControlSettings field; derived bindings follow
 *    a rebindable command; the rebind fallback refuses keys owned by other commands
 *  - every non-debug command is reachable on touch; gestures sit on an existing button
 *  - README.md's controls section equals the generated one (`--write` regenerates it)
 *
 *   npx tsx tools/commands-check.ts [--write]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { COMMANDS, COMMAND_GROUPS, controlRows, isFreeFor, keyMap, keysOf, type CommandId } from '../src/client/commands';
import { GLYPHS } from '../src/ui/icons';
import { defaultSettings } from '../src/ui/settings';

const errors: string[] = [];
const fail = (m: string) => errors.push(m);

// ------------------------------------------------------------------ registry

const ids = new Set<CommandId>();
for (const c of COMMANDS) {
  if (ids.has(c.id)) fail(`duplicate command id ${c.id}`);
  ids.add(c.id);
  if (!c.label || !c.short) fail(`${c.id}: label and short caption are required`);
  if (!GLYPHS.includes(c.glyph)) fail(`${c.id}: unknown glyph '${c.glyph}' (src/ui/icons.ts)`);
  if (!c.keys.length && c.scope !== 'view') fail(`${c.id}: no default binding`);
  if (c.rebind && !(c.rebind in defaultSettings().controls)) fail(`${c.id}: rebind field '${c.rebind}' is not a ControlSettings field`);
  if (c.follows) {
    const src = COMMANDS.find((x) => x.id === c.follows!.command);
    if (!src) fail(`${c.id}: follows unknown command ${c.follows.command}`);
    else if (keysOf(c.id).join() !== keysOf(src.id).map((k) => `${c.follows!.modifier}+${k}`).join()) fail(`${c.id}: default keys must equal ${c.follows.modifier} + ${src.id}'s keys`);
  }
  if (!c.debug && c.touch.method === 'none') fail(`${c.id}: not reachable on touch (give it a touch method or mark it debug)`);
  if (c.touch.method !== 'none' && !c.touch.text) fail(`${c.id}: touch.text is required`);
  if (c.touch.method === 'gesture') {
    const host = COMMANDS.find((x) => x.id === c.touch.on);
    if (!host || host.touch.method !== 'button') fail(`${c.id}: gesture must sit on a command with a touch button`);
    if (!c.touch.gesture) fail(`${c.id}: gesture kind missing`);
  }
}

// Bindings: one owner each (across all scopes), except the intended shared Esc.
const SHARED = new Set(['Escape:pause,targetClear']);
const owners = new Map<string, CommandId[]>();
for (const scope of ['game', 'ui', 'view'] as const) {
  for (const [k, list] of keyMap(scope)) owners.set(k, [...(owners.get(k) ?? []), ...list]);
}
for (const [k, list] of owners) {
  if (list.length > 1 && !SHARED.has(`${k}:${[...list].sort().join(',')}`)) fail(`binding ${k} is used by ${list.join(', ')}`);
}

// Rebinding falls back to the default instead of stealing another command's key.
for (const c of COMMANDS.filter((x) => x.rebind)) {
  for (const [k, list] of owners) {
    if (list.includes(c.id) || list.every((id) => COMMANDS.find((x) => x.id === id)?.follows?.command === c.id)) continue;
    if (k.includes('+')) continue;
    if (isFreeFor(k, c.id)) fail(`${c.id}: ${k} (owned by ${list.join(', ')}) would be accepted as a rebind`);
    if (keysOf(c.id, { [c.id]: k })[0] !== c.keys[0]) fail(`${c.id}: override ${k} must fall back to ${c.keys[0]}`);
  }
  const free = 'KeyQ';
  if (keysOf(c.id, { [c.id]: free })[0] !== free) fail(`${c.id}: a free key (${free}) must be accepted`);
}

// ------------------------------------------------------------------ README

const BEGIN = '<!-- controls:begin (generated by tools/commands-check.ts --write) -->';
const END = '<!-- controls:end -->';

function readmeSection(): string {
  const rows = controlRows({}, { debug: true });
  const out: string[] = [BEGIN, '', '| Keyboard & mouse | Action | Touch |', '| --- | --- | --- |'];
  for (const g of COMMAND_GROUPS) {
    for (const r of rows.filter((x) => x.group === g)) {
      const keys = r.keys.map((alt) => alt.join(alt.includes('…') ? ' ' : alt.length > 1 && r.ids.length === 1 ? '+' : ' ')).join(' / ');
      const touch = r.touch.method === 'none' ? '—' : r.touch.text;
      out.push(`| ${keys.replace(/\|/g, '\\|')} | ${r.label} | ${touch} |`);
    }
  }
  out.push('', 'Tab targeting is rebindable in Settings → Controls (Shift + the key cycles backwards); the touch layout, stick size, look sensitivity and button opacity are adjustable there too. Touch controls appear as soon as the screen is touched and step aside when a mouse or keyboard is used.', '', END);
  return out.join('\n');
}

const readme = readFileSync('README.md', 'utf8');
const a = readme.indexOf(BEGIN), b = readme.indexOf(END);
const section = readmeSection();
if (a < 0 || b < 0) fail('README.md: controls section markers missing');
else {
  const current = readme.slice(a, b + END.length);
  if (current.replace(/\r\n/g, '\n') !== section) {
    if (process.argv.includes('--write')) {
      writeFileSync('README.md', readme.slice(0, a) + section + readme.slice(b + END.length));
      console.log('README.md controls section regenerated');
    } else fail('README.md controls section is out of date — run: npx tsx tools/commands-check.ts --write');
  }
}

if (errors.length) {
  for (const e of errors) console.error('✗', e);
  process.exit(1);
}
console.log(`commands-check: ${COMMANDS.length} commands OK`);
